project:
  type: website

website:
  title: "Perspektywy2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Ranking2024
      - href: dashboard.qmd
        text: Ranking_2024
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



