---
title: "Ranking"
format: dashboard
---
### Row {.tabset title="Kategoria 1"}


```{r}
#| echo: false
#| include: false
library(readxl)
library(tidyverse)
```

```{r}
#| echo: false
#| include: false
dane=read_excel("p_2024.xlsx",sheet="p_2024")
dane$Uczelnia <- factor(dane$Uczelnia, levels = dane$Uczelnia[order(dane$Ranking_2024)])

d1=dane %>% 
  filter(ind=="UE")

dane2=dane[c(1:25,35,46,48,70),]
nazwy=names(d1)
```





```{r}
#| title: Prestiż
nazwa=nazwy[10]
ggplot(dane2, aes(x = Uczelnia, y = v1, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()


nazwa=nazwy[11]
ggplot(dane2, aes(x = Uczelnia, y = v2, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

```


```{r}
#| title: Absolwenci na rynku pracy
nazwa=nazwy[12]
ggplot(dane2, aes(x = Uczelnia, y = v3, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

nazwa=nazwy[13]
ggplot(dane2, aes(x = Uczelnia, y = v4, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

```


```{r}
#| title: Potencjał naukowy
nazwa=nazwy[14]
ggplot(dane2, aes(x = Uczelnia, y = v5, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

nazwa=nazwy[15]
ggplot(dane2, aes(x = Uczelnia, y = v6, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

nazwa=nazwy[16]
ggplot(dane2, aes(x = Uczelnia, y = v7, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

nazwa=nazwy[17]
ggplot(dane2, aes(x = Uczelnia, y = v8, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()
```



```{r}
#| title: Innowacyjność
nazwa=nazwy[18]
ggplot(dane2, aes(x = Uczelnia, y = v9, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

nazwa=nazwy[19]
ggplot(dane2, aes(x = Uczelnia, y = v10, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

nazwa=nazwy[20]
ggplot(dane2, aes(x = Uczelnia, y = v11, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()
```


```{r}
#| title: Efektywność naukowa
nazwa=nazwy[21]
ggplot(dane2, aes(x = Uczelnia, y = v12, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

nazwa=nazwy[22]
ggplot(dane2, aes(x = Uczelnia, y = v13, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

nazwa=nazwy[23]
ggplot(dane2, aes(x = Uczelnia, y = v14, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

nazwa=nazwy[24]
ggplot(dane2, aes(x = Uczelnia, y = v15, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

nazwa=nazwy[25]
ggplot(dane2, aes(x = Uczelnia, y = v16, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

nazwa=nazwy[26]
ggplot(dane2, aes(x = Uczelnia, y = v17, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

nazwa=nazwy[27]
ggplot(dane2, aes(x = Uczelnia, y = v18, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

nazwa=nazwy[28]
ggplot(dane2, aes(x = Uczelnia, y = v19, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

nazwa=nazwy[29]
ggplot(dane2, aes(x = Uczelnia, y = v20, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

```


```{r}
#| title: Warunki kształcenia
nazwa=nazwy[30]
ggplot(dane2, aes(x = Uczelnia, y = v21, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

nazwa=nazwy[31]
ggplot(dane2, aes(x = Uczelnia, y = v22, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

```


```{r}
#| title: Umiędzynarodowienie
nazwa=nazwy[32]
ggplot(dane2, aes(x = Uczelnia, y = v23, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

nazwa=nazwy[33]
ggplot(dane2, aes(x = Uczelnia, y = v24, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

nazwa=nazwy[34]
ggplot(dane2, aes(x = Uczelnia, y = v25, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

nazwa=nazwy[35]
ggplot(dane2, aes(x = Uczelnia, y = v26, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

nazwa=nazwy[36]
ggplot(dane2, aes(x = Uczelnia, y = v27, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

nazwa=nazwy[37]
ggplot(dane2, aes(x = Uczelnia, y = v28, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

nazwa=nazwy[38]
ggplot(dane2, aes(x = Uczelnia, y = v29, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

nazwa=nazwy[39]
ggplot(dane2, aes(x = Uczelnia, y = v30, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()

nazwa=nazwy[40]
ggplot(dane2, aes(x = Uczelnia, y = v31, fill = kolor)) +
  geom_bar(stat = "identity") +
  labs(x="",y=nazwa)+
  scale_fill_identity()+
  coord_flip()


```
