---
title: "Podsumowanie"
---

Ranking Perpektywy 2024

Tabela. Zysk punktowy w Rankingu przy poprawie naszej punktacji w danej kategorii o 10% lub 50%

+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | Lp. |     | Kategoria                                     |     | Wzrost o 10% |     | Wzrost o 50% |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 1   |     | Ocena przez kadrę akademicką (10%)            |     | 0,041        |     | 0,205        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 2   |     | Uznanie międzynarodowe (2%)                   |     | 0,019        |     | 0,097        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 3   |     | Wynagrodzenia (6%)                            |     | 0,333        |     | 1,663        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 4   |     | Zatrudnienie (6%)                             |     | 0,380        |     | 1,898        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 5   |     | Ewaluacja działalności naukowej (10%)         |     | 0,571        |     | 2,857        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 6   |     | Nasycenie kadry osobami… (1%)                 |     | 0,063        |     | 0,317        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 7   |     | Uprawnienia habilitacyjne i doktorskie (1%)   |     | 0,007        |     | 0,037        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 8   |     | Kształcenie doktorantów (1%)                  |     | 0,044        |     | 0,220        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 9   |     | Patenty … w Polsce (3%)                       |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 10  |     | Patenty … za granicą (3%)                     |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 11  |     | SDG (2%)                                      |     | 0,067        |     | 0,337        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 12  |     | Efektywność pozyskiwania środków (6%)         |     | 0,224        |     | 1,122        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 13  |     | Efektywność pozyskiwania … UE (5%)            |     | 0,042        |     | 0,210        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 14  |     | Rozwój kadry własnej (3%)                     |     | 0,040        |     | 0,198        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 15  |     | Nadane stopnie i tytuły (3%)                  |     | 0,109        |     | 0,546        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 16  |     | Publikacje (3%)                               |     | 0,062        |     | 0,312        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 17  |     | Cytowania (3%)                                |     | 0,079        |     | 0,394        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 18  |     | FWCI (3%)                                     |     | 0,104        |     | 0,522        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 19  |     | FWVI (3%)                                     |     | 0,131        |     | 0,656        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 20  |     | Top10 (3%)                                    |     | 0,103        |     | 0,513        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 21  |     | Dostępność dla studentów... (5%)              |     | 0,160        |     | 0,798        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 22  |     | Akredytacje (5%)                              |     | 0,061        |     | 0,307        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 23  |     | Studenci cudzoziemcy (3%)                     |     | 0,030        |     | 0,149        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 24  |     | Studiujący w j. obcym (3%)                    |     | 0,078        |     | 0,390        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 25  |     | ICI (2%)                                      |     | 0,065        |     | 0,325        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 26  |     | Uniwersytety europejskie (1%)                 |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 27  |     | Nauczyciele … z zagranicy (1%)                |     | 0,001        |     | 0,005        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 28  |     | Wymiana kadry (1%)                            |     | 0,084        |     | 0,419\*      |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 29  |     | Wymiana … (wyjazdy, 1,5%)                     |     | 0,041        |     | 0,205        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 30  |     | Wymiana… (przyjazdy, 1,5%)                    |     | 0,016        |     | 0,079        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     | 31  |     | Wielokulturowość... (1%)                      |     | 0,006        |     | 0,028        |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     |                                               |     |              |     |              |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+
|     |     |     | **Suma**                                      |     | 2,96         |     | 14,8         |    |
+-----+-----+-----+-----------------------------------------------+-----+--------------+-----+--------------+----+

\*) nie mamy możliwości zwiększenia o 50%, ponieważ mamy 84p, a max to 100p.

**Wyjaśnienie:**

Jeśli np. nadanych zostało 7 stopni doktora (7p) i 2 stopnie dra hab. (3p), to wzrost o 10% oznacza nadanie np. 11 stopni doktora (ewentualnie np. .8 stopni doktora i 2 stopni dra hab.).

Dane z Komitetów Naukowych:

Rok 2023: habilitacje: xxxx, doktoraty: xxxx

Rok 2024 (przewidywane): habilitacje: xxxx, doktoraty: xxxx

Elastyczność

Zwiększamy naszą punktację (efekty) w danej kategorii o x % (10 lub 50) – jaki jest zysk w finalnej punktacji (wpływa na to aktualna liczba punktów oraz waga kategorii).

Najbardziej „zyskowne”
